<template>
	<div class="main-container">
        <div class="inputWithIcon" v-if="searchNotActive">
            <input class="search-input" v-model="message" placeholder="Search..." />
            <i class="las la-times" @click="closeSearch()"></i>
        </div>
		
		<div class="header-container" v-if="searchActive">
			<div class="header-menu">
				<h1>Resturant</h1>
				<ul>
					<li>
						<a href="#home">Home</a>
					</li>
					<li>
						<a href="#news">News</a>
					</li>
					<li>
						<a href="#contact">Contact</a>
					</li>
					<li>
						<a href="#about">About</a>
					</li>
				</ul>
			</div>

			<div class="search-container">
				<i class="las la-search" id="search-icon" @click="toggleSearch()"></i>
				<i class="las la-hamburger"></i>
			</div>
		</div>
		
	</div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";

@Component
export default class header extends Vue {
	toggleNav = false;
	isActive = true;
    searchActive = true;
    searchNotActive = false;

	toggleSearch() {
        this.searchActive = false;
        this.searchNotActive = true;
    }

    closeSearch(){
        this.searchActive = true;
        this.searchNotActive = false;
    }
}
</script>

<style lang="scss" scoped>
.header-container {
	margin-top: 30px;
	padding: 20px;
	display: flex;
	flex-direction: row;
	font-family: "Nobile", sans-serif;
	justify-content: space-between;
	height: 50px;
	color: #7c9f40;
}
.main-container {
	overflow: hidden;
}
.header-menu {
	display: flex;
	flex-direction: row;
	justify-content: flex-start;
	align-items: center;
	ul {
		list-style-type: none;
		margin: 0;
		padding: 0;
		overflow: hidden;
		font-weight: lighter;
	}

	li {
		float: left;
	}

	li a {
		display: block;
		color: #7c9f40;
		text-align: center;
		padding: 16px;
		text-decoration: none;
		font-size: 25px;
	}

	li a:hover {
		background-color: #1111115b;
		color: #fff;
	}
}
h1 {
	margin-right: 40px;
	cursor: pointer;
}

.search-container {
	display: flex;
	flex-direction: row;
	justify-content: flex-end;
	align-content: center;
}
.las {
	font-size: 45px;
	margin-left: 20px;
	margin-right: 10px;
}

.menu-item {
	font-size: 5em;
	list-style: none;
	text-transform: uppercase;
	font-family: sans-serif;
	text-align: center;
	cursor: pointer;
	transition: margin-left 0.5s ease-out, opacity 0.5s ease-out;
}

.selected {
	margin-left: -90px;
}

.menu-item > .arrow {
	opacity: 0;
	transition: opacity 0.7s ease-out;
}

.selected > .arrow {
	opacity: 1;
}

.dimmed {
	opacity: 0.3;
}

.char {
	display: inline-block;
	min-width: 0.3em;
}
.char {
	transition: transform 0.3s;
}
.selected .char {
	transform: scaleX(-1);
}

/* Side bar animation */
/* ----------------------------------------------
 * Generated by Animista on 2020-1-9 22:0:15
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-left {
	0% {
		-webkit-transform: translateX(0);
		transform: translateX(0);
	}
	100% {
		-webkit-transform: translateX(-100px);
		transform: translateX(-100px);
	}
}
@keyframes slide-left {
	0% {
		-webkit-transform: translateX(0);
		transform: translateX(0);
	}
	100% {
		-webkit-transform: translateX(-100px);
		transform: translateX(-100px);
	}
}

/* *
* ---------------
* side bar class
* ---------------
*/
.slide-left {
	position: absolute;
	top: 0;
	bottom: 0;
	left: 0;
	right: 0;
	height: 100%;
	width: 100vw;
	z-index: 1;
	background: #00000073;

	-webkit-animation: slide-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
	animation: slide-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* 
Main nav container
 */

.main-nav-container {
	display: none;
}

/* Search animation */
#search-icon {
}
.search-input {
	width: 100%;
	height: 100px;
	padding-left: 20px;
	padding-right: 20px;
	font-size: 30px;
	-webkit-box-shadow: 0px 15px 35px -5px rgba(0, 0, 0, 0.62);
	-moz-box-shadow: 0px 15px 35px -5px rgba(0, 0, 0, 0.62);
    box-shadow: 0px 15px 35px -5px rgba(0, 0, 0, 0.62);
    border: none;
    background: #ddddddb6;
    -webkit-animation: scale-in-hor-right 0.5s ease-in both;
	        animation: scale-in-hor-right 0.5s ease-in both;
}

/**
 * ----------------------------------------
 * animation scale-in-hor-right
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-hor-right {
  0% {
    -webkit-transform: scaleX(0);
            transform: scaleX(0);
    -webkit-transform-origin: 100% 100%;
            transform-origin: 100% 100%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleX(1);
            transform: scaleX(1);
    -webkit-transform-origin: 100% 100%;
            transform-origin: 100% 100%;
    opacity: 1;
  }
}
@keyframes scale-in-hor-right {
  0% {
    -webkit-transform: scaleX(0);
            transform: scaleX(0);
    -webkit-transform-origin: 100% 100%;
            transform-origin: 100% 100%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleX(1);
            transform: scaleX(1);
    -webkit-transform-origin: 100% 100%;
            transform-origin: 100% 100%;
    opacity: 1;
  }
}
.inputWithIcon {
  position: relative;
}

.inputWithIcon i {
  position: absolute;
  right: 0;
  top: 8px;
  padding: 9px 8px;
  color: rgb(19, 19, 19);
  transition: 0.3s;
}

</style>
